#pragma once

namespace pop::shader_consts {

#ifdef __cplusplus
#include <cstdint>
using uint = std::uint32_t;
#define POP_CONST constexpr
#else // ^^ cpp vv slang
#define POP_CONST const
#endif

static POP_CONST uint GPU_WAVE_SIZE = 32;

static POP_CONST uint CS_UPLOAD_MESHES_GROUP_SIZE_X = 32;
static POP_CONST uint CS_CLEAR_INSTANCE_COUNT_GROUP_SIZE_X = 32;
static POP_CONST uint CS_SIMULATION_STEP_GROUP_SIZE_X = 256;

static POP_CONST uint CS_SIMULATION_ACCELERATION_GRID_SORT_PREPARE_GROUP_SIZE_X = 256;

static POP_CONST uint CS_SIMULATION_ACCELERATION_GRID_BITONIC_SORT_GROUP_SIZE_X = 256;

static POP_CONST uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_RADIX_BITS = 8;
static POP_CONST uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_RADIX_BUCKETS = 1 << CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_RADIX_BITS;

static POP_CONST uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_RADIX_MASK = CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_RADIX_BUCKETS - 1;

static POP_CONST uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_BUILD_KEYS_PER_THREAD = 8;
static POP_CONST uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_BUILD_KEYS_PER_GROUP =
    CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_BUILD_KEYS_PER_THREAD * CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_RADIX_BUCKETS;

static POP_CONST uint CS_SIMULATION_ACCELERATION_GRID_SCAN_BOUNDS_GROUP_SIZE_X = 256;

static POP_CONST uint CS_SIMULATION_INFLUENCE_STEP_GROUP_SIZE_X = 256;

static POP_CONST uint CS_BUILD_INDIRECT_INSTANCE_COUNT_GROUP_SIZE_X = 256;
static POP_CONST uint CS_BUILD_INDIRECT_FIRST_INSTANCE_GROUP_SIZE_X = GPU_WAVE_SIZE;
static POP_CONST uint CS_BUILD_INSTANCE_BUFFER_GROUP_SIZE_X = 256;

static POP_CONST uint MAX_DRAW_COMMANDS = GPU_WAVE_SIZE;

} // namespace pop::shader_consts
