#pragma once

namespace pop::shader_consts {

#ifdef __cplusplus
#include <cstdint>
using uint = std::uint32_t;
#endif

static const uint GPU_WAVE_SIZE = 32;

static const uint CS_UPLOAD_MESHES_GROUP_SIZE_X = 32;
static const uint CS_CLEAR_INSTANCE_COUNT_GROUP_SIZE_X = 32;
static const uint CS_SIMULATION_STEP_GROUP_SIZE_X = 256;

static const uint CS_SIMULATION_ACCELERATION_GRID_SORT_PREPARE_GROUP_SIZE_X = 256;
static const uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_BUILD_GROUP_SIZE_X = 256;
static const uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_RADIX_BITS = 8;
static const uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_RADIX_BUCKETS = 1 << CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_RADIX_BITS;
static const uint CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_RADIX_MASK = CS_SIMULATION_ACCELERATION_GRID_RADIX_SORT_HISTOGRAM_RADIX_BUCKETS - 1;

static const uint CS_BUILD_INDIRECT_INSTANCE_COUNT_GROUP_SIZE_X = 256;
static const uint CS_BUILD_INDIRECT_FIRST_INSTANCE_GROUP_SIZE_X = GPU_WAVE_SIZE;
static const uint CS_BUILD_INSTANCE_BUFFER_GROUP_SIZE_X = 256;

static const uint MAX_DRAW_COMMANDS = GPU_WAVE_SIZE;

} // namespace pop::shader_consts